import 'package:firebase_auth/firebase_auth.dart';
import 'package:flutter/material.dart';

class HelpProvider with ChangeNotifier {
  final _auth = FirebaseAuth.instance;
  var loggedInUser;
  String userID;

  List<String> helpline_services = [
    "NATIONAL EMERGENCY NUMBER",
    "POLICE",
    "FIRE",
    "AMBULANCE",
    "Disaster Management Services",
    "Women Helpline",
    "Women Helpline - ( Domestic Abuse )",
    "Air Ambulance",
    "Aids Helpline",
    "Anti Poison ( New Delhi )",
    "Disaster Management ( N.D.M.A )",
    "EARTHQUAKE / FLOOD / DISASTER  ( N.D.R.F Headquarters )",
    "Deputy Commissioner Of Police",
    "Railway Enquiry",
    "Senior Citizen Helpline",
    "Medical Helpline",
    "Railway Accident Emergency Service",
    "Road Accident Emergency Service",
    "Road Accident Emergency Service On National Highway For Private Operators",
    "ORBO Centre, AIIMS (For Donation Of Organ) Delhi",
    "Kisan Call Centre",
    "Relief Commissioner For Natural Calamities",
    "Children In Difficult Situation",
    "All India Institute of Medical Sciences (AIIMS) Poison Control",
    "Tourist Helpline",
    "LPG Leak Helpline",
    "KIRAN MENTAL HEALTH Helpline",
  ];
  List<String> helpline_numbers = [
    "112",
    "100",
    "101",
    "102",
    "108",
    "1091",
    "181",
    "9540161344",
    "1097",
    "1066",
    "1078",
    "011-24363260",
    "1094",
    "139",
    "1291",
    "108",
    "1072",
    "1073",
    "1033",
    "1060",
    "1551",
    "1070",
    "1098",
    "011-26593677",
    "1800111363",
    "1906",
    "18005990019",
  ];

  List<String> helpline_images = [
    "nat_emer_no-removebg-preview.png",
    "police.jpg",
    "fire.jpg",
    "ambulance.jpg",
    "disaster.jpeg",
    "woman_helpline.jpg",
    "dom_abuse.jpg",
    "air_ambulance.jpg",
    "aids.png",
    "poison.png",
    "disaster.jpeg",
    "ndrf.png",
    "police.jpg",
    "railway.jpg",
    "senior_citizen.png",
    "ambulance.jpg",
    "railway.jpg",
    "ndrf.png",
    "disaster.jpeg",
    "orbo_aiims.png",
    "farmers.jpg",
    "disaster.jpeg",
    "child.jpg",
    "orbo_aiims.png",
    "tourist.jpg",
    "lpg.jpeg",
    "mental.jpg",
  ];
}
